### ISSUE TITLE
Consistent error trying to download.

### ISSUE THREAD

**Issue by Hime0698** [RikudouSage/GogDownloader#3]
Hey, I love this tool and it's been working great, but all of a sudden when I'm trying to download, I get this issue:
![CleanShot 2024-05-15 at 11 10 21](https://github.com/RikudouSage/GogDownloader/assets/26724000/dec7d4fe-a554-42be-ac44-0c6a2ed0e91b)

**Comment by RikudouSage** [comment]
Should be fixed in latest release.

**Comment by duran55** [comment]
i am using the latest version: gog-downloader 1.4.1
the same error still appears.

**Comment by RikudouSage** [comment]
Can you set an environment variable `GOG_DOWNLOADER_DEBUG` to the value 1?

**Comment by duran55** [comment]
$ ./gog-downloader update
 1/9 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  11% - Mirror's Edge™Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#136
  #message: """
    Attempted to load class "SimpleXMLElement" from the global namespace.\n
    Did you forget a "use" statement?
    """
  #code: 0
  #file: "phar:///storage/Games Archive/GOG/gog-downloader/src/Service/OwnedItemsManager.php"
  #line: 194
  trace: {
    phar:///storage/Games Archive/GOG/gog-downloader/src/Service/OwnedItemsManager.php:194 {
      App\Service\OwnedItemsManager->getChecksum(DownloadDescription $download, GameDetail $game, int $httpTimeout = 3): ?string^
      › try {
      ›     $response = new SimpleXMLElement($response->getContent());
      › } catch (ClientExceptionInterface | TransportExceptionInterface | ServerExceptionInterface) {
    }
    phar:///storage/Games Archive/GOG/gog-downloader/src/Service/OwnedItemsManager.php:260 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/src/Service/OwnedItemsManager.php:229 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/src/Service/OwnedItemsManager.php:117 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/src/Command/UpdateDatabaseCommand.php:164 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/src/Service/RetryService.php:24 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/src/Command/UpdateDatabaseCommand.php:153 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/vendor/symfony/console/Command/Command.php:326 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/vendor/symfony/console/Application.php:1078 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/vendor/symfony/console/Application.php:324 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/vendor/symfony/console/Application.php:175 { …}
    phar:///storage/Games Archive/GOG/gog-downloader/bin/app.php:21 { …}
    /storage/Games Archive/GOG/gog-downloader:12 { …}
  }
}

**Comment by duran55** [comment]
PHP 8.3.6 (cli) (built: Jun 13 2024 15:23:20) (NTS)
Ubuntu 24.04 LTS

**Comment by duran55** [comment]
It seems I forgot to install simplexml. After `sudo apt install php8.3-xml` now it is working properly.

**Comment by RikudouSage** [comment]
Great, thanks for the info! Closing the issue as it's unrelated.
